### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by Hotfirenet** [Z-Wave-Me/z-way-mini-ui#1]
hello,
or should we place the files?
in the directory / opt / z-way / htdocs?
or does he install an apache server?

thank you

**Comment by PoltoS** [comment]
You can put it in any place (even open it as a file without web server using file:///<path to file>/z-way-demo-ui.html).

There is a simple for that allows you to connect to any existing RaZberry or Z-Cloud service (both are compatible). For this you need to fill the URL (like http://<Raspberry Pi IP>:8083 or https://z-cloud.z-wave.me:<port>) and username and password (only for Z-Cloud).

**Comment by Hotfirenet** [comment]
Ok thank you I'll try
